import type { SimulationBody } from "./types.ts";
import {
  SOLAR_MASS_KG,
  SOLAR_RADIUS_M,
  SOLAR_LUMINOSITY_W,
  EARTH_MASS_KG,
  EARTH_RADIUS_M,
  JUPITER_MASS_KG,
  JUPITER_RADIUS_M,
  G_CODATA_2022,
  C_M_S,
} from "./constants.ts";

export interface SimulationPreset {
  id: string;
  name: string;
  category: "planet" | "star" | "compact" | "minor";
  description: string;
  createBody: (options?: { id?: string; name?: string; position?: [number, number, number]; velocity?: [number, number, number] }) => SimulationBody;
}

export const PRESETS: SimulationPreset[] = [
  {
    id: "preset-earth-like",
    name: "Earth-like Rocky Planet",
    category: "planet",
    description: "Terrestrial rocky planet with liquid water potential, silicate mantle, and nitrogen-oxygen atmosphere.",
    createBody: (opts) => ({
      id: opts?.id ?? `planet-${Date.now()}`,
      name: opts?.name ?? "Earth-like Planet",
      classification: "planet",
      gravityRole: "massive",
      mass: EARTH_MASS_KG,
      radius: EARTH_RADIUS_M,
      density: 5515,
      position: opts?.position ?? [149597870700, 0, 0],
      velocity: opts?.velocity ?? [0, 29780, 0],
      color: "#4b8bf5",
      rotation: { periodSeconds: 86400, axialTiltDeg: 23.44 },
      thermal: { surfaceTempK: 288, equilibriumTempK: 255, albedo: 0.306, emissivity: 0.95 },
      physicsCapabilityFlags: { hasAtmosphere: true, isLuminous: false },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.0 Earth mass baseline" },
        radius: { kind: "estimated", method: "Template preset", note: "1.0 Earth radius baseline" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-gas-giant",
    name: "Jovian Gas Giant",
    category: "planet",
    description: "Massive hydrogen-helium gas giant with strong radiation belts and rapid rotation.",
    createBody: (opts) => ({
      id: opts?.id ?? `gasgiant-${Date.now()}`,
      name: opts?.name ?? "Gas Giant",
      classification: "planet",
      gravityRole: "massive",
      mass: JUPITER_MASS_KG,
      radius: JUPITER_RADIUS_M,
      density: 1326,
      position: opts?.position ?? [778500000000, 0, 0],
      velocity: opts?.velocity ?? [0, 13070, 0],
      color: "#c99039",
      rotation: { periodSeconds: 35730, axialTiltDeg: 3.13 },
      thermal: { surfaceTempK: 165, equilibriumTempK: 110, albedo: 0.503, emissivity: 0.98 },
      physicsCapabilityFlags: { hasAtmosphere: true, isLuminous: false },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.0 Jupiter mass baseline" },
        radius: { kind: "estimated", method: "Template preset", note: "1.0 Jupiter radius baseline" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-asteroid",
    name: "Carbonaceous Asteroid",
    category: "minor",
    description: "Small primitive C-type asteroid treated as a tracer mass by default.",
    createBody: (opts) => ({
      id: opts?.id ?? `asteroid-${Date.now()}`,
      name: opts?.name ?? "C-type Asteroid",
      classification: "asteroid",
      gravityRole: "tracer",
      mass: 5e18,
      radius: 15000,
      density: 2200,
      position: opts?.position ?? [414000000000, 0, 0],
      velocity: opts?.velocity ?? [0, 17800, 0],
      color: "#7a7772",
      rotation: { periodSeconds: 28800, axialTiltDeg: 12.0 },
      thermal: { albedo: 0.05 },
      physicsCapabilityFlags: { hasAtmosphere: false, isLuminous: false },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "Small asteroid tracer" },
        radius: { kind: "estimated", method: "Template preset", note: "15 km mean radius" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-comet",
    name: "Volatile Comet",
    category: "minor",
    description: "Icy planetesimal on a highly eccentric trajectory with active sublimation volatiles.",
    createBody: (opts) => ({
      id: opts?.id ?? `comet-${Date.now()}`,
      name: opts?.name ?? "Active Comet",
      classification: "comet",
      gravityRole: "tracer",
      mass: 1e14,
      radius: 5000,
      density: 600,
      position: opts?.position ?? [800000000000, 0, 0],
      velocity: opts?.velocity ?? [0, 8000, 0],
      color: "#8ce8ff",
      rotation: { periodSeconds: 43200, axialTiltDeg: 45.0 },
      thermal: { albedo: 0.04 },
      physicsCapabilityFlags: { hasAtmosphere: false, isLuminous: false },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "Cometary nucleus tracer" },
        radius: { kind: "estimated", method: "Template preset", note: "5 km nucleus" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-sun-like-star",
    name: "Sun-like Main Sequence Star (G2V)",
    category: "star",
    description: "Main-sequence yellow dwarf star with convective envelope, core fusion, and coronal emission.",
    createBody: (opts) => ({
      id: opts?.id ?? `star-${Date.now()}`,
      name: opts?.name ?? "Sun-like Star",
      classification: "star",
      gravityRole: "massive",
      mass: SOLAR_MASS_KG,
      radius: SOLAR_RADIUS_M,
      density: 1408,
      position: opts?.position ?? [0, 0, 0],
      velocity: opts?.velocity ?? [0, 0, 0],
      color: "#ffe082",
      rotation: { periodSeconds: 2160000, axialTiltDeg: 7.25 },
      thermal: { surfaceTempK: 5778 },
      radiative: { luminosityWatts: SOLAR_LUMINOSITY_W },
      physicsCapabilityFlags: { isLuminous: true },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.0 Solar mass" },
        radius: { kind: "estimated", method: "Template preset", note: "1.0 Solar radius" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-white-dwarf",
    name: "Degenerate White Dwarf",
    category: "compact",
    description: "Compact stellar remnant supported by electron degeneracy pressure; extremely high surface gravity.",
    createBody: (opts) => ({
      id: opts?.id ?? `whitedwarf-${Date.now()}`,
      name: opts?.name ?? "White Dwarf",
      classification: "white-dwarf",
      gravityRole: "massive",
      mass: 0.6 * SOLAR_MASS_KG,
      radius: 0.009 * SOLAR_RADIUS_M, // ~Earth radius
      density: 1e9,
      position: opts?.position ?? [0, 0, 0],
      velocity: opts?.velocity ?? [0, 0, 0],
      color: "#e0f7fa",
      rotation: { periodSeconds: 86400, axialTiltDeg: 0 },
      thermal: { surfaceTempK: 25000 },
      radiative: { luminosityWatts: 0.001 * SOLAR_LUMINOSITY_W },
      physicsCapabilityFlags: { isLuminous: true, isRelativistic: true },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "0.6 Solar mass carbon-oxygen core" },
        radius: { kind: "estimated", method: "Template preset", note: "Degenerate carbon-oxygen radius (~6000 km)" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-neutron-star",
    name: "Neutron Star",
    category: "compact",
    description: "Ultra-dense stellar remnant supported by neutron degeneracy pressure. Deep gravitational potential well.",
    createBody: (opts) => ({
      id: opts?.id ?? `neutronstar-${Date.now()}`,
      name: opts?.name ?? "Neutron Star",
      classification: "neutron-star",
      gravityRole: "massive",
      mass: 1.4 * SOLAR_MASS_KG,
      radius: 12000, // 12 km
      density: 4e17,
      position: opts?.position ?? [0, 0, 0],
      velocity: opts?.velocity ?? [0, 0, 0],
      color: "#80deea",
      rotation: { periodSeconds: 0.1, axialTiltDeg: 15 },
      thermal: { surfaceTempK: 1e6 },
      compact: {
        magneticFieldTesla: 1e8,
        spinPeriodSeconds: 0.1,
      },
      physicsCapabilityFlags: { isRelativistic: true },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.4 Solar masses (Chandrasekhar limit scale)" },
        radius: { kind: "estimated", method: "Template preset", note: "12 km canonical radius" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-pulsar",
    name: "Radio Pulsar",
    category: "compact",
    description: "Rapidly rotating neutron star with intense synchrotron radiation beams aligned to misaligned magnetic poles.",
    createBody: (opts) => ({
      id: opts?.id ?? `pulsar-${Date.now()}`,
      name: opts?.name ?? "Pulsar",
      classification: "pulsar",
      gravityRole: "massive",
      mass: 1.4 * SOLAR_MASS_KG,
      radius: 11000,
      density: 5e17,
      position: opts?.position ?? [0, 0, 0],
      velocity: opts?.velocity ?? [0, 0, 0],
      color: "#00e5ff",
      rotation: { periodSeconds: 0.033, axialTiltDeg: 20 },
      compact: {
        magneticFieldTesla: 1e8,
        beamConeAngleDeg: 12,
        magneticAxisTiltDeg: 45,
        spinPeriodSeconds: 0.033, // Crab pulsar rate
      },
      physicsCapabilityFlags: { isRelativistic: true },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.4 Solar mass rotating neutron star" },
        radius: { kind: "estimated", method: "Template preset", note: "11 km radius" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-magnetar",
    name: "Magnetar",
    category: "compact",
    description: "Neutron star possessing an extreme magnetic field (~10^10 to 10^11 Tesla) generating high-energy gamma-ray flares.",
    createBody: (opts) => ({
      id: opts?.id ?? `magnetar-${Date.now()}`,
      name: opts?.name ?? "Magnetar",
      classification: "magnetar",
      gravityRole: "massive",
      mass: 1.5 * SOLAR_MASS_KG,
      radius: 11500,
      density: 4.7e17,
      position: opts?.position ?? [0, 0, 0],
      velocity: opts?.velocity ?? [0, 0, 0],
      color: "#b388ff",
      rotation: { periodSeconds: 5.0, axialTiltDeg: 10 },
      compact: {
        magneticFieldTesla: 1e11,
        magneticAxisTiltDeg: 30,
        spinPeriodSeconds: 5.0,
      },
      physicsCapabilityFlags: { isRelativistic: true },
      provenance: {
        mass: { kind: "estimated", method: "Template preset", note: "1.5 Solar mass extreme-B neutron star" },
        radius: { kind: "estimated", method: "Template preset", note: "11.5 km radius" },
        state: { kind: "custom", method: "Preset instantiation" },
      },
    }),
  },
  {
    id: "preset-black-hole",
    name: "Stellar-Mass Black Hole",
    category: "compact",
    description: "Non-spinning Schwarzschild black hole with an event horizon at rs = 2GM/c^2. Material crossing rs is captured.",
    createBody: (opts) => {
      const mass = 10 * SOLAR_MASS_KG;
      const rs = (2 * G_CODATA_2022 * mass) / (C_M_S * C_M_S);
      return {
        id: opts?.id ?? `blackhole-${Date.now()}`,
        name: opts?.name ?? "Stellar Black Hole",
        classification: "black-hole",
        gravityRole: "massive",
        mass,
        radius: rs, // Physical radius is the event horizon
        position: opts?.position ?? [0, 0, 0],
        velocity: opts?.velocity ?? [0, 0, 0],
        color: "#111115",
        compact: {
          schwarzschildRadiusM: rs,
        },
        physicsCapabilityFlags: { isRelativistic: true },
        provenance: {
          mass: { kind: "estimated", method: "Template preset", note: "10 Solar masses stellar remnant" },
          radius: { kind: "calculated", method: "rs = 2GM/c^2", note: "Exact Schwarzschild radius" },
          state: { kind: "custom", method: "Preset instantiation" },
        },
      };
    },
  },
];
