import type { CelestialBody } from "../types.ts";
import { satelliteCountOf } from "../satellites/index.ts";

/** Canonical figures: NASA planetary and Moon fact sheets (retrieved 2026-09-16). */
export const EARTH: CelestialBody = {
  identity: {
    id: "earth",
    name: "Earth",
    epithet: "The living marble",
    kind: "planet",
    parentId: "sun",
    category: "Terrestrial",
    color: "#6ea8d8",
  },
  physical: {
    meanRadiusKm: 6371.0,
    diameterKm: 12742,
    massKg24: 5.972,
    massEarths: 1,
    gravityG: 1,
    escapeVelocityKmS: 11.19,
    densityGCm3: 5.51,
  },
  orbit: {
    semiMajorAxisAu: 1.0,
    periodDays: 365.25,
    inclinationDeg: 0, // by definition — the ecliptic reference plane
    eccentricity: 0.017,
    orbitalSpeedKmS: 29.8,
  },
  rotation: {
    periodHours: 23.93,
    axialTiltDeg: 23.44,
  },
  temperature: {
    meanC: 15,
    noteC: { min: -89, max: 57 }, // record surface extremes
  },
  atmosphere: {
    pressureBars: 1.014,
    composition: [
      { name: "Nitrogen", share: "78 %" },
      { name: "Oxygen", share: "21 %" },
      { name: "Argon", share: "0.9 %" },
      { name: "Water vapour / CO₂", share: "variable trace" },
    ],
    note: "The only atmosphere known to be maintained by a biosphere — oxygen is a metabolic waste product that would otherwise vanish.",
  },
  interior:
    "Solid inner iron core, liquid outer core (the dynamo behind the magnetic field), silicate mantle, and a thin moving crust of plates.",
  magneticField: "Strong dipole generated by the convecting liquid-iron outer core; deflects the solar wind and guides aurorae.",
  moonSystem: {
    confirmedCount: satelliteCountOf("earth"),
    asOf: "2026-08-15",
    sourceIds: ["nasa-moon-factsheet", "nasa-solar-system-exploration"],
    note: "1 large natural satellite, the Moon — large enough relative to Earth that the pair is often described as a double planet system.",
  },
  features: [
    {
      id: "pacific-ocean",
      name: "Pacific Ocean",
      kind: "region",
      approximateLocation: true,
      summary: "The largest single surface feature in the solar system's habitable zone — 165 million km² of liquid water.",
    },
  ],
  blurb:
    "The only known world with liquid oceans and a biosphere. A magnetic field and a restless moon keep the climate within a narrow, habitable band.",
  notes: {
    climate:
      "Axial tilt drives the seasons; oceans transport heat poleward; the Moon steadies the tilt against chaotic drift over millions of years.",
    exploration:
      "The only body humans have walked on besides Earth: twelve Apollo astronauts, 1969–1972. Continuous orbital habitation since 2000 (ISS).",
  },
  sources: [{ id: "nasa-planetary-factsheet" }, { id: "nasa-solar-system-exploration" }],
  retrieved: "2026-09-16",
};
